Enable the use of pre-trained models
vitillo/profondo pull request #16
Opened 2017-04-23 19:43 UTC by Dexterp37

Initial commit, not ready for review and not working.

2017-04-24 11:13 UTC, vitillo requested changes

2017-04-24 11:13 UTC, vitillo commented on profondo/cnn.py
> +        train_datagen = ImageDataGenerator(rescale=1. / 255)
Our images are already in the [0, 1] range so they don't need rescaling.

2017-04-24 12:51 UTC, vitillo requested changes

2017-04-24 12:51 UTC, vitillo commented on profondo/cnn.py
> +        train_datagen = ImageDataGenerator()
Might be worthwhile removing the generator since we don't use it anymore.

2017-04-24 16:27 UTC, vitillo requested changes

2017-04-24 16:27 UTC, vitillo commented on profondo/cnn.py
> +                      callbacks=[reduce_lr],
Why did you remove the other callbacks?

2017-04-25 06:39 UTC, vitillo requested changes

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +    if exists(MODEL_FILENAME):
The model has to exist, if not it's fine to raise an exception.

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +        prediction_proba = model.predict(x_val)
Why has this call been changed?

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +    model = build_pre_trained(args.pre_trained, x_train, y_train, x_val, y_val)\
We should use the non-pretrained model if no pre-trained network name is specified.

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +        bottleneck_train = model.predict(x_train, num_train_batches, verbose=True)
I don't think `num_train_batches` makes sense how it's defined and used when passed to the `batch_size` argument of `model.predict()`. Can we just pass `args.batch_size`?

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +                      batch_size=init_batch,
Please use `args.batch_size`.

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +            ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=10e-6),
Don't we want to save only the best model in case this ends up overfitting?

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +                      epochs=50,
Please use `args.epochs`.

2017-04-25 06:39 UTC, vitillo commented on profondo/cnn.py
> +                        optimizer=keras.optimizers.SGD(lr=1e-4, momentum=0.9))
Any particular reason we are using SGD instead of Adam?

2017-04-25 09:20 UTC, Dexterp37 commented on profondo/cnn.py
> +            ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=10e-6),
Good point, fixed.

2017-04-25 09:23 UTC, Dexterp37 commented on profondo/cnn.py
> +        prediction_proba = model.predict(x_val)
`predict_proba` isn't defined for `Model` (see [here](https://keras.io/models/model/)) and it's just a legacy wrapper for `predict` in `Sequential` ([implementation](https://github.com/fchollet/keras/blob/master/keras/models.py#L982)).

2017-04-25 09:36 UTC, Dexterp37 commented on profondo/cnn.py
> +                      epochs=50,
Fixed!

2017-04-25 09:36 UTC, Dexterp37 commented on profondo/cnn.py
> +                      batch_size=init_batch,
Fixed!

2017-04-25 09:47 UTC, Dexterp37 commented on profondo/cnn.py
> +                        optimizer=keras.optimizers.SGD(lr=1e-4, momentum=0.9))
It seems to work better than Adam when using a pre-trained network on my system (Adam diverges, while SGD seem to converge to a nicer optimum)

2017-04-25 09:48 UTC, Dexterp37 commented on profondo/cnn.py
> +    if exists(MODEL_FILENAME):
If the model doesn't exist, `load_model` builds a new one from scratch. I'm happy to leave this as it is anyway, as long as we're aware of that :)

2017-04-25 09:57 UTC, vitillo commented on profondo/cnn.py
> +    if exists(MODEL_FILENAME):
Right, but we really want to evaluate the best model on the test data there so I think it makes sense to assert on the existence of the model.

2017-04-25 10:03 UTC, vitillo approved these changes
LGTM

2017-04-25 10:04 UTC, merged